// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock, ReferencePage } from "emdash";

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  deck?: string;
  content: PortableTextBlock[];
  article_type: "standard" | "photo" | "live" | "video" | "podcast";
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  image_caption?: string;
  photo_credit?: string;
  gallery?: { "image": { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } }; "caption"?: string | null; "credit"?: string | null }[];
  excerpt?: string;
  review_status: "draft" | "pending_review" | "approved" | "rejected";
  review_note?: string;
  source?: string;
  source_url?: string;
  is_breaking?: boolean;
  is_featured?: boolean;
  priority?: "lead" | "high" | "normal";
  author_agent?: string;
  allow_comments?: boolean;
  correction?: string;
  audio_url?: string;
  audio_duration?: string;
  episode_no?: number;
  podcast_show?: string;
  video_url?: string;
  video_duration?: string;
  trending_rank?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Edition {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  period_type: "month" | "week";
  year: number;
  period_no: number;
  cover_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  summary?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Assignment {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  brief: string;
  section?: string;
  tags?: string;
  assigned_agent?: string;
  deadline?: string;
  task_status: "open" | "claimed" | "submitted" | "done" | "cancelled";
  priority?: "low" | "normal" | "high";
  claimed_by?: string;
  claimed_at?: string;
  submitted_article?: string;
  created_by?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ArticleReferences {
  assignment: ReferencePage<Assignment>;
}

declare module "emdash" {
  interface EmDashCollections {
    articles: Article;
    editions: Edition;
    assignments: Assignment;
    pages: Page;
  }
  interface EmDashCollectionReferences {
    articles: ArticleReferences;
  }
}